module.exports=[{
            type:1,
            name:"单曲",
            relist:{},
            klass:'songs',
            offset:0,
            limit:20
        },{
            type:10,
            name:"专辑",
            relist:{},
            klass:'album',
            offset:0,
            limit:20
        }]
